---
- name: Deploy Scientific Calculator Container
  hosts: localhost
  become: false

  tasks:

    - name: Pull Docker image
      command: /usr/local/bin/docker pull rish9981/scientific-calculator:latest

    - name: Stop old container
      command: /usr/local/bin/docker stop calculator-container
      ignore_errors: yes

    - name: Remove old container
      command: /usr/local/bin/docker rm calculator-container
      ignore_errors: yes

    - name: Run new container
      command: /usr/local/bin/docker run -dit --name calculator-container rish9981/scientific-calculator
